import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { STATE_DIR } from "../hooks/state.js";
import { log } from "../log.js";
import { upsertInstallManifest } from "./manifest.js";
import type { AgentIntegration } from "./types.js";

/** The project-local OpenCode plugin file blastcheck installs (under `cwd`). */
const OPENCODE_CONFIG_FILES = [".opencode/plugins/blastcheck.ts"] as const;

/**
 * Canonical, shared `.blastcheck/` evidence paths. OpenCode reuses the SAME
 * trajectory/baseline/scorecard trio as Claude Code / Codex (FR23) — the audit
 * core is agent-agnostic, so there is one canonical evidence trio per repo.
 */
const OPENCODE_EVIDENCE_PATHS = {
  trajectory: `${STATE_DIR}/trajectory.jsonl`,
  baseline: `${STATE_DIR}/baseline`,
  scorecard: `${STATE_DIR}/scorecard.json`,
} as const;

/**
 * The real, dependency-free, blastcheck-managed OpenCode plugin (Story 3.2).
 *
 * It is a valid OpenCode plugin module — an exported async function receiving the
 * plugin context (`{ $, directory, client }`) and returning a hooks object — that
 * forwards the session-start (`session.created`), tool-completed
 * (`tool.execute.after`), and session-idle (`session.idle`) lifecycle events to
 * `blastcheck hook opencode <event>` via Bun's `$` shell (FR33/FR34).
 *
 * Story 1.1 wiring fix (§6.5): `session.created` and `session.idle` are members of
 * the SDK `Event` union, NOT hook keys — the OpenCode `Hooks` interface has no such
 * keys, so the original object-key handlers never fired. They are now subscribed
 * through the generic `event` hook (`event: async ({ event }) => …` switching on
 * `event.type`); `tool.execute.after` is a genuine interceptor key and stays a
 * top-level key. The first line is the ownership/idempotency marker (the analogue of
 * Codex's `blastcheck hook codex …` command-string marker), so a future uninstall
 * can recognise the managed file. CAPTURE + AUDIT + SURFACE: the `session.idle`
 * end-of-turn event triggers `blastcheck hook opencode stop`, which runs the shared
 * `runStop` → `runAudit` over the captured trajectory (FR39) — the OpenCode analogue
 * of Claude Code's `Stop` hook — but ONLY when an output guard confirms the turn
 * produced assistant text (idle carries only `{ sessionID }`, so the guard fetches the
 * session messages via `client`; it FAILS OPEN on any error so a real `fail` verdict
 * is never dropped). Story 1.3 added the SURFACE step: the toast/feedback primitives
 * live on `client`, which exists ONLY here in the plugin runtime (the `hook opencode
 * stop` Node process has no `client`), so that CLI process can only DESCRIBE the
 * surfacing — it emits a single surface JSON line `{ message, variant, feedback? }`
 * on stdout (and fires the `fail` desktop alert, a client-free shell-out). The plugin
 * CAPTURES that stdout, parses the last non-empty line, and renders it natively:
 * `client.tui.showToast` on EVERY verdict (the brief pass line included) and, when
 * feedback is opted in, `client.session.prompt` on a warn/fail. All wording lives in
 * tested TypeScript (`verdict-text.ts`); this plugin is a thin render shim.
 * `session.idle` may fire multiple times per session; each fire re-audits the same
 * state and overwrites the scorecard idempotently (`.quiet().nothrow()` shell-out, no
 * loop guard in the plugin).
 *
 * Dependency-free (NFR15): it imports NOTHING — no `@opencode-ai/plugin`, no
 * package import — so OpenCode's Bun runtime never attempts any module
 * resolution; it uses only the context `$` (Bun shell), `directory`, and the
 * context-provided `client` (the typed SDK HTTP client over the local server).
 *
 * Injection-safe + non-fatal (NFR6/NFR15): the JSON payload is piped to the
 * command's stdin via a `Response` body (`< ${new Response(json)}`) and Bun
 * auto-escapes interpolated values — never a `bash -c` and never
 * string-concatenated — while `.quiet().nothrow()` + try/catch guarantee a
 * non-zero exit, stderr, or a missing `blastcheck` binary can never throw into
 * the OpenCode session.
 *
 * NOTE: the OpenCode event names + `(input, output)` field shapes below are
 * best-effort from the June-2026 docs and remain doc-derived — Story 3.3's live
 * capture attempt loaded the plugin (its `{ directory }` context confirmed) but
 * could not drive a real tool-call round-trip in the dev env, so the FR31
 * live-capture debt is still open (see the fixtures README / deferred-work.md). The
 * `tool.execute.after` payload is pre-shaped into the Claude `PostToolUse` contract
 * here so the DEFAULT adapter normalizes it; FR35's dedicated `src/trajectory/`
 * adapter stays conditional and was NOT built (no real sample disproved coverage).
 * If a future real payload cannot be cleanly mapped, that is the FR35 re-scope —
 * not a silent change here.
 */
const OPENCODE_PLUGIN_SOURCE = `// blastcheck-managed: do not edit by hand.
// Generated by \`blastcheck init --agent opencode\` (Story 3.1; lifecycle capture wired in Story 3.2; audit-on-idle wired in Story 3.3; event-hook wiring fixed in Story 1.1; verdict surfacing wired in Story 1.3).
// Forwards OpenCode lifecycle events to \`blastcheck hook opencode <event>\`, so
// working in OpenCode as usual captures a canonical trajectory under
// .blastcheck/trajectory.jsonl and, on session.idle, triggers the shared audit
// (blastcheck hook opencode stop -> runAudit) AND surfaces the verdict natively.
// session.created and session.idle are SDK \`Event\` union members (NOT hook keys),
// so they are subscribed via the generic \`event\` hook switching on event.type;
// tool.execute.after is a real interceptor key. session.idle only surfaces when the
// turn produced assistant text (a messages lookup via the typed client; fail-open on
// any error). SURFACING (Story 1.3): the toast/feedback primitives live on \`client\`,
// which exists only in this plugin runtime — the \`hook opencode stop\` CLI process
// has none — so that process emits a surface JSON line { message, variant, feedback? }
// on stdout (and fires the fail desktop alert itself). This plugin CAPTURES that
// stdout, parses the last non-empty line, and renders it: client.tui.showToast on
// every verdict, plus client.session.prompt (opt-in feedback) on warn/fail. A
// failed/empty/garbage parse degrades quietly (no toast, no throw) — the
// .blastcheck/scorecard.json mirror stays the source of truth.
//
// Dependency-free (NFR15): this file imports nothing and uses only the plugin
// context ($ = Bun shell, directory = project dir, client = typed SDK client). The
// shell-out is injection-safe (Bun auto-escapes interpolated values; the JSON
// payload is piped via a Response body to stdin, never string-concatenated) and
// non-fatal (.quiet().nothrow() + try/catch), so it can never break the session.

export const BlastcheckPlugin = async ({ $, directory, client }) => {
  // Forward one lifecycle event to the blastcheck CLI on stdin. \`event\` is a
  // fixed literal ("session-start" | "post-tool-use" | "stop"), never user input.
  const forward = async (event, payload) => {
    try {
      const json = JSON.stringify({ ...payload, cwd: directory });
      await $\`blastcheck hook opencode \${event} < \${new Response(json)}\`.quiet().nothrow();
    } catch {
      // Swallow: a hook must never destabilize the OpenCode session (NFR6).
    }
  };

  // Idle guard: did the turn that just ended actually produce assistant text?
  // session.idle carries only { sessionID }, so fetch the session messages and
  // inspect the latest assistant message's text parts. FAIL-OPEN — any throw,
  // empty result, or unexpected shape returns true so a real \`fail\` verdict is
  // never silently dropped (a redundant audit is cheap and idempotent).
  const producedAssistantOutput = async (sessionID) => {
    // Fail-open if the idle event carried no usable session id (never issue a
    // bad messages lookup with id=undefined; a real \`fail\` must not be dropped).
    if (!sessionID) return true;
    try {
      const messages = await client.session.messages({ path: { id: sessionID } });
      if (!Array.isArray(messages) || messages.length === 0) return true;
      let latestAssistant;
      for (const m of messages) {
        if (m?.info?.role === "assistant") latestAssistant = m;
      }
      if (!latestAssistant || !Array.isArray(latestAssistant.parts)) return true;
      return latestAssistant.parts.some(
        (p) => p?.type === "text" && typeof p.text === "string" && p.text.trim().length > 0,
      );
    } catch {
      return true;
    }
  };

  // Surface the end-of-turn verdict natively. Shell the SAME audit command the
  // generic forward() uses (\`blastcheck hook opencode stop\`, { cwd } piped on
  // stdin via a Response — injection-safe), but CAPTURE its stdout: the OpenCode
  // reporter emits a single surface JSON line { message, variant, feedback? }
  // there (the .blastcheck/scorecard.json mirror stays the source of truth, and
  // the fail desktop alert already fired CLI-side). The toast/feedback primitives
  // are methods on \`client\`, which exists ONLY here — so the CLI describes the
  // surfacing and THIS renders it. Degrade quietly on any error / empty / non-JSON
  // output: no toast, no throw (the mirror still holds the verdict).
  const surfaceVerdict = async (sessionID) => {
    try {
      const json = JSON.stringify({ cwd: directory });
      const stdout = await $\`blastcheck hook opencode stop < \${new Response(json)}\`
        .quiet()
        .nothrow()
        .text();
      // Parse the LAST non-empty line as JSON (robust against any stray output).
      const lines = String(stdout)
        .split("\\n")
        .map((line) => line.trim())
        .filter((line) => line.length > 0);
      if (lines.length === 0) return;
      let surface;
      try {
        surface = JSON.parse(lines[lines.length - 1]);
      } catch {
        return; // non-JSON noise on stdout → no toast, no throw
      }
      if (!surface || typeof surface.message !== "string") return;
      // Visible toast on EVERY verdict (the brief pass "all clear" line included).
      // variant is cosmetic; pass it through (the reporter mapped it to the SDK
      // tui.showToast enum: success | warning | error).
      await client.tui.showToast({ body: { message: surface.message, variant: surface.variant } });
      // Opt-in feedback (warn/fail; default OFF): inject the detail as a new prompt
      // so the agent can act on it. KNOWN CAVEAT: a prompt starts a new turn ->
      // which goes idle -> re-audits; if still warn/fail it can fire again (a
      // potential loop). That is intrinsic to the cross-agent feedback primitive
      // and is exactly why §7.2 made it opt-in/default-OFF; no stateful loop guard
      // here (it would touch the statelessness invariant). On a converging session
      // (agent fixes the issue -> pass) feedback stops naturally. Needs a real
      // session id — skip injection if idle carried none (the toast still showed).
      if (surface.feedback && sessionID) {
        await client.session.prompt({
          path: { id: sessionID },
          body: { parts: [{ type: "text", text: surface.feedback }] },
        });
      }
    } catch {
      // Swallow: surfacing must never destabilize the OpenCode session (NFR6).
    }
  };

  return {
    // Completed tool execution → append one canonical trajectory line. Shape the
    // OpenCode event into the Claude-compatible PostToolUse payload so the default
    // adapter normalizes it (bash -> args.cmd, edit/write -> args.path). This is a
    // REAL interceptor key and stays a top-level key.
    "tool.execute.after": async (input, output) => {
      await forward("post-tool-use", {
        tool_name: input?.tool,
        tool_input: output?.args,
        tool_response: { ...(output?.metadata ?? {}), stdout: output?.output },
      });
    },
    // Generic bus-event hook. session.created and session.idle are SDK \`Event\`
    // union members — NOT hook keys — so they are delivered ONLY here; switch on
    // event.type. The whole body is wrapped so it can never throw into the session.
    event: async ({ event }) => {
      try {
        if (event.type === "session.created") {
          // Fresh session start → record the pre-commitment HEAD (resets stale state).
          await forward("session-start", { source: "startup" });
        } else if (event.type === "session.idle") {
          // Agent finished its turn (OpenCode's analogue of Claude Code's Stop) →
          // run the audit AND surface the verdict natively, but only when the turn
          // produced assistant output (suppress empty-turn idle fires). May fire
          // repeatedly; each fire re-audits and overwrites the scorecard
          // idempotently (no loop guard). Read sessionID defensively: a malformed
          // idle envelope (missing properties) must fail OPEN to the audit, not be
          // swallowed by the catch.
          const sessionID = event.properties?.sessionID;
          if (await producedAssistantOutput(sessionID)) {
            await surfaceVerdict(sessionID);
          }
        }
      } catch {
        // Swallow: a hook must never destabilize the OpenCode session (NFR6).
      }
    },
  };
};
`;

export const opencodeIntegration: AgentIntegration = {
  id: "opencode",
  displayName: "OpenCode",
  async install(options) {
    const pluginDir = join(options.cwd, ".opencode", "plugins");
    const pluginPath = join(pluginDir, "blastcheck.ts");

    // Strict idempotency / no churn (AC4): read the existing managed file (if
    // any) and write ONLY when the canonical content differs. A genuinely-
    // missing file (ENOENT) means "write it"; any other read error
    // (EACCES/EISDIR/ENOTDIR/…) propagates rather than silently clobbering a
    // file we merely failed to read — mirror `readHookSettings`'s ENOENT-only
    // degrade.
    let existing: string | undefined;
    try {
      existing = await readFile(pluginPath, "utf8");
    } catch (err) {
      if ((err as NodeJS.ErrnoException)?.code !== "ENOENT") throw err;
    }

    if (existing === OPENCODE_PLUGIN_SOURCE) {
      log("info", `init opencode: ${OPENCODE_CONFIG_FILES[0]} already current`);
    } else {
      // `mkdir(..., { recursive: true })` is a safe no-op when the directory
      // already exists and never touches sibling plugin files (AC2). The write
      // step runs BEFORE the manifest upsert, so a failed write (e.g.
      // `.opencode/plugins` occupied by a file) throws before any manifest is
      // written (AC: failure contract).
      await mkdir(pluginDir, { recursive: true });
      await writeFile(pluginPath, OPENCODE_PLUGIN_SOURCE, "utf8");
      log("info", `init opencode: wrote ${OPENCODE_CONFIG_FILES[0]}`);
    }

    // Trust is `trusted`: OpenCode auto-loads local `.opencode/plugins/*` at
    // startup with no per-plugin trust-review gate (unlike Codex `/hooks`), so
    // there is no pending review state to record. Runtime verification ("did
    // OpenCode actually load it?") is a separate concern — Story 3.4.
    const entry = {
      agent: "opencode" as const,
      displayName: "OpenCode",
      configFiles: [...OPENCODE_CONFIG_FILES],
      evidencePaths: { ...OPENCODE_EVIDENCE_PATHS },
      trust: "trusted" as const,
      updatedAt: new Date().toISOString(),
    };
    await upsertInstallManifest(options.cwd, entry);

    // Defensive copies so callers can't mutate the canonical manifest metadata.
    return {
      agent: entry.agent,
      configFiles: [...entry.configFiles],
      evidencePaths: { ...entry.evidencePaths },
      trust: entry.trust,
    };
  },
};
