import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { STATE_DIR } from "../hooks/state.js";
import { log } from "../log.js";
import { upsertInstallManifest } from "./manifest.js";
import type { AgentIntegration } from "./types.js";

/** The project-local OpenCode plugin file blastcheck installs (under `cwd`). */
const OPENCODE_CONFIG_FILES = [".opencode/plugins/blastcheck.ts"] as const;

/**
 * Canonical, shared `.blastcheck/` evidence paths. OpenCode reuses the SAME
 * trajectory/baseline/scorecard trio as Claude Code / Codex (FR23) — the audit
 * core is agent-agnostic, so there is one canonical evidence trio per repo.
 */
const OPENCODE_EVIDENCE_PATHS = {
  trajectory: `${STATE_DIR}/trajectory.jsonl`,
  baseline: `${STATE_DIR}/baseline`,
  scorecard: `${STATE_DIR}/scorecard.json`,
} as const;

/**
 * The minimal, dependency-free, blastcheck-managed plugin scaffold (Story 3.1).
 *
 * It is a syntactically valid OpenCode plugin module — an exported async
 * function returning a hooks object — but it subscribes to NOTHING: lifecycle
 * event subscriptions and the `blastcheck hook opencode <event>` shell-out are
 * added in Story 3.2. The first line is the ownership/idempotency marker (the
 * analogue of Codex's `blastcheck hook codex …` command-string marker), so a
 * future uninstall can recognise the managed file.
 *
 * Dependency-free (NFR15): it imports NOTHING — the `@opencode-ai/plugin` type
 * import is type-only/erased, but the scaffold omits it entirely so OpenCode's
 * Bun runtime never attempts any module resolution.
 */
const OPENCODE_PLUGIN_SOURCE = `// blastcheck-managed: do not edit by hand.
// Generated by \`blastcheck init --agent opencode\` (Story 3.1).
// Lifecycle event subscriptions and audit wiring are added in Story 3.2.
// Dependency-free: this file intentionally imports nothing (NFR15) and shells out
// to the \`blastcheck\` binary at runtime once Story 3.2 wires the handlers.

export const BlastcheckPlugin = async ({ $, directory }) => {
  // Story 3.2 will subscribe to session/tool lifecycle events here and forward
  // them to \`blastcheck hook opencode <event>\` via Bun's \`$\` shell.
  return {};
};
`;

export const opencodeIntegration: AgentIntegration = {
  id: "opencode",
  displayName: "OpenCode",
  async install(options) {
    const pluginDir = join(options.cwd, ".opencode", "plugins");
    const pluginPath = join(pluginDir, "blastcheck.ts");

    // Strict idempotency / no churn (AC4): read the existing managed file (if
    // any) and write ONLY when the canonical content differs. A genuinely-
    // missing file (ENOENT) means "write it"; any other read error
    // (EACCES/EISDIR/ENOTDIR/…) propagates rather than silently clobbering a
    // file we merely failed to read — mirror `readHookSettings`'s ENOENT-only
    // degrade.
    let existing: string | undefined;
    try {
      existing = await readFile(pluginPath, "utf8");
    } catch (err) {
      if ((err as NodeJS.ErrnoException)?.code !== "ENOENT") throw err;
    }

    if (existing === OPENCODE_PLUGIN_SOURCE) {
      log("info", `init opencode: ${OPENCODE_CONFIG_FILES[0]} already current`);
    } else {
      // `mkdir(..., { recursive: true })` is a safe no-op when the directory
      // already exists and never touches sibling plugin files (AC2). The write
      // step runs BEFORE the manifest upsert, so a failed write (e.g.
      // `.opencode/plugins` occupied by a file) throws before any manifest is
      // written (AC: failure contract).
      await mkdir(pluginDir, { recursive: true });
      await writeFile(pluginPath, OPENCODE_PLUGIN_SOURCE, "utf8");
      log("info", `init opencode: wrote ${OPENCODE_CONFIG_FILES[0]}`);
    }

    // Trust is `trusted`: OpenCode auto-loads local `.opencode/plugins/*` at
    // startup with no per-plugin trust-review gate (unlike Codex `/hooks`), so
    // there is no pending review state to record. Runtime verification ("did
    // OpenCode actually load it?") is a separate concern — Story 3.4.
    const entry = {
      agent: "opencode" as const,
      displayName: "OpenCode",
      configFiles: [...OPENCODE_CONFIG_FILES],
      evidencePaths: { ...OPENCODE_EVIDENCE_PATHS },
      trust: "trusted" as const,
      updatedAt: new Date().toISOString(),
    };
    await upsertInstallManifest(options.cwd, entry);

    // Defensive copies so callers can't mutate the canonical manifest metadata.
    return {
      agent: entry.agent,
      configFiles: [...entry.configFiles],
      evidencePaths: { ...entry.evidencePaths },
      trust: entry.trust,
    };
  },
};
